version: '2'
services:
  web:
    image: "masaruz/nodejs-lb"
    links: 
      - mongo
    ports:
      - 80:3000
    environment:
      - expt=604800s
      - exp=2419200s

  mongo:
    image: "mongo"
    ports:
      - 27017:27017